version: "2.0"
services:
  db:
    image: "mongo:latest"
    command: "mongod --smallfiles --quiet"
    ports:
      - "27018:27017"
    volumes:
      - "/docker_volumes/mongo:/data/db"

  web:
    build: "."
    command: "bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0'"
    ports:
      - "3001:3000"
    links:
      - "db"
    volumes:
      - ".:/app"
